### PR TITLE
WIP: replace clj-native with techascent's jna library

### PR DESCRIPTION
**Pull request by hlolli**
Using newer up-to-date library for the native-bindings should fix some amount of accumulated bugs.

Currently WIP.

### CODE REVIEW

**Comment by harold** [comment]
@cnuernber - mild relevance to your interests.

**Comment by pfeodrippe** [comment]
@plexus Not sure if it’s worth waiting more maturity on project panama instead of trying to use JNA. Also I don’t see which bugs this is fixing

**Comment by plexus** [comment]
I think in general we need to ask if the effort of building an embeddable libscsynth on multiple platforms, packaging it for distribution, and then dealing with JNA (or a JNA alternative) to use it is providing enough benefits to justify the time investment. What does this get us that running an external server doesn't give us? I don't want to have that discussion on this ticket though, we already had some discussion on #overtone on Clojurians ([#overtone 2023-11-06](https://clojurians-log.clojureverse.org/overtone/2023-11-06/1699342543.317049)), and we'll move it either to a separate ticket here or to the mailing list. Just want to register here my stance that I think we should consider approaches that allow us to drop this whole thing and simplify things.

**Comment by hlolli** [comment]
I agree, this is madness to maintain, all the 3rd party libraries and the symbols for specific compiler versions. I vote for relying on having the users install supercollider themselves. If it works, it's super nice and makes Overtone work out of the box. Maybe supercollider will work with universal binary like wasm in the future, then we could revisit this. In any case, I think I wont be spending more time on this PR.

**Comment by samaaron** [comment]
@plexus @hlolli - completely agreed. I think if your'e building an end-user app like Sonic Pi then getting everything working out-of-the-box makes sense. However, for a library like Overtone I think it was the wrong approach in hindsight.

When we were first working on it we were trying out best to lower the friction to enabling people to start making sounds with Clojure. Having the goal of just adding a dependency and using a namespace to get everything running definitely helped with that.

However, whilst this does reduce friction in the installation dimension, there are still other significant frictions to overcome - learning how to design synths to name just one. I think it's probably reasonable to assume that if someone has the goal of using Overtone, they're ok with the fact they're going to have to put in this time - at which point installing SuperCollider isn't actually that much more of a chore.

Essentially I thought that making it super simple to get started would get loads of people jamming Overtone - but it turned out that the friction for learning how to make a sound was way more obstructive than I imagined.

Therefore the gains in optimising this don't really match the massively increased complexity of building and distributing libscsynth and maintaining the JVM->native bridges necessary to work with it.

Also, a crash in libscsynth will crash the JVM. Using an external scsynth binary provides additional reliability.

**Pull request closed without merging**
