### PR TITLE
ClojureScript compatibility for overtone.music.pitch via CLJX

### PR DESCRIPTION
**Pull request by triss**
This change request makes `overtone.music.pitch` and namespaces it uses available in CLJS.

Changes:

Added CLJX to build dependencies and configured.

Enabled cross compilation of overtone.music.pitch by:
- renaming it and it's dependencies to .cljx files
- making sure exceptions thrown in CLJS are `js/Error.`
- making ratios floating point values in CLJS.
- migrating macros to separate file.

As a side effect `algo.chance`, `algo.scaling`, `helpers.map` and `helpers.old-contrib` were also made available to CLJS.

### CODE REVIEW

**Comment by rogerallen** [comment]
I'm curious about the motivation for this.  Why do you want to make only this particular file ClojureScript compatible?

**Comment by triss** [comment]
Hi Roger, motivation stems from the fact I've been looking at building a "reactive" wrapper around the WebAudio API over the past few weeks.

I just wanted the scales and functions for converting from midi->hz etc. for my experiments.

Now I've thought about it I feel there'd be quite a bit of value splitting the overtone.music.pitch out of overtone that want to do musical work using clojure(script) but without utilising the SuperCollider back end.

**Comment by brunchboy** [comment]
The same thing can be said for `overtone.music.rhythm`; for now I just copied that source into my project because I do not yet need the SuperCollider stuff, and am pulling in `at-at` and OSC separately. Perhaps most of the `music` packages would be useful independently?

**Comment by triss** [comment]
I'm closing this PR since `cljc` is the favoured approach for making namespaces available across both Clojure and CLJS currently.

**Pull request closed without merging**
