### PR TITLE
midi-poly-player ignores unmapped control changes

### PR DESCRIPTION
**Pull request by derwentx**
solves https://github.com/overtone/overtone/issues/356

### CODE REVIEW

**Comment by samaaron** [comment]
Help me get my head back into this code base - why is it necessary to ignore unmapped control changes? :-)

**Comment by derwentx** [comment]
@samaaron well basically, it causes a null pointer exception when it tries to destruct nil, the result of getting a non-mapped control from mapping. so if you have your midi instrument mapped to handle changes from only one knob, and you bump an adjacent knob, it tries to process that control change event too and fails. the linked issue has an example that explains it better

**Comment by samaaron** [comment]
Happy to merge this then :-)

**Comment by samaaron** [comment]
However, you might want to look at Clojure's `when-let` :-)

**Comment by derwentx** [comment]
thanks! yeah that would probably be more succinct :P

**Pull request merged**
